
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: sliv_bank_chrun_transformation
      description: "Extracting month and year from date column and credit score based on score value"
      columns:
          - name: customer_id
            descrpition: "THe customer is unique value"
            test:
                - unique
                - not_null

